### ISSUE TITLE
windows 7 powershell 2.0 version issue

### ISSUE THREAD

**Issue by jishuzhain** [nmantani/PS-TrustedDocuments#1]
This line of code doesn't work under powershell 2.0 version.
$timestamp_unix = $timestamp_unix -shl (64+29)  

After modifying the code, it can barely execute normally.
$timestamp_unix = $timestamp_unix * 9903520314283042199192993792

**Comment by nmantani** [comment]
Thank you for your feedback! I have added PowerShell 2.0 support.
